spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_ex?characterEncoding=utf-8&serverTimezone=Asia/Seoul&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: mybatis/mapper/*.xml